### ISSUE TITLE
Vlan Tag

### ISSUE THREAD

**Issue by jzadir** [lnxbil/docker-machine-driver-proxmox-ve#11]
Hi! 
Great Work!
Is there a way to set the vlan tag on the network interface ?

**Comment by lnxbil** [comment]
@mhermosi is working on that right now.

**Comment by mhermosi** [comment]
I've made a big rework on the options to fine tune the VM on Proxmox, still working on some stuff.. I have a stable version but still needs work to be done.

**Comment by lnxbil** [comment]
Is there somehing I can merge?

**Comment by bemanuel** [comment]
I had create a way to do this, I submit a PR and it is working

**Comment by bemanuel** [comment]
> Is there somehing I can merge?

I put a PR to be approved

**Comment by lnxbil** [comment]
New version with a lot of fixes and merged PR. Please try again and report back.
