### ISSUE TITLE
Storage not found

### ISSUE THREAD

**Issue by ArnaudTA** [lnxbil/docker-machine-driver-proxmox-ve#12]
Hello, I'm trying your driver that seems very interesting ! Perhaps I have a problem with "--proxmox-storage" option what ever I use it return "storage xxxx not found". This error happen even if I don't use option.

Here my command :
```docker-machine create --driver proxmox-ve --proxmox-disksize-gb "16" --proxmox-driver-debug --proxmox-guest-password "tcuser" --proxmox-host "192.168.0.100" --proxmox-image-file "local:./boot2docker.iso" --proxmox-memory-gb "8" --proxmox-node prox --proxmox-password deploy --proxmox-realm "pve" --proxmox-resty-debug --proxmox-storage "disque_2" --proxmox-storage-type "raw" --proxmox-user "deploy" node1```

And the error message :
```Running pre-create checks...
(node1) {"time":"2019-08-15T22:23:03.100958642+02:00","level":"INFO","prefix":"-","file":"proxmoxdriver.go","line":"58","message":"Create called"}
(node1) {"time":"2019-08-15T22:23:03.100978417+02:00","level":"INFO","prefix":"-","file":"proxmoxdriver.go","line":"58","message":"Connecting to 192.168.0.100 as deploy@pve with password 'deploy'"}
(node1) {"time":"2019-08-15T22:23:03.135099605+02:00","level":"INFO","prefix":"-","file":"proxmoxdriver.go","line":"58","message":"Connected to PVE version '5.4'"}
(node1) {"time":"2019-08-15T22:23:03.135121594+02:00","level":"INFO","prefix":"-","file":"proxmoxdriver.go","line":"64","message":"Retrieving next ID"}
(node1) {"time":"2019-08-15T22:23:03.137414645+02:00","level":"INFO","prefix":"-","file":"proxmoxdriver.go","line":"58","message":"Next ID was '102'"}
Error with pre-create check: "storage 'disque_2' not found"
```
I join a screenshot of my proxmox disk maybe i didn't understand something. 
![Capture d’écran de 2019-08-15 22-26-45](https://user-images.githubusercontent.com/33383276/63124541-d24bb300-bfab-11e9-981e-1b917b7ca92e.png)

Thanks for your work and your help

**Comment by ArnaudTA** [comment]
okay sorry I'm bad ! Not your fault, I created a user just for this driver and forget to give him perms...

**Comment by lnxbil** [comment]
Glad it worked out.
