### ISSUE TITLE
returned diskname is not correct

### ISSUE THREAD

**Issue by Sellto** [lnxbil/docker-machine-driver-proxmox-ve#16]
Hello,

I try to use your driver (v2) as a `node-driver` in Rancher to provide a Kubernetes cluster.
But i have a issue, the logs return me this error :
`Error creating machine: Error in driver during machine creation: returned diskname is not correct.`

<img width="1272" alt="Rancher Error" src="https://user-images.githubusercontent.com/17011743/70229354-59d55180-1756-11ea-8eb4-676b7796dee5.png">

However, as you can see in the screen shot, the disk is correctly created but the VM isn't created:

<img width="1198" alt="proxmox" src="https://user-images.githubusercontent.com/17011743/70229401-707ba880-1756-11ea-8658-442bc5164a2e.png">

Here is my proxmox `node template` in Rancher:

![proxmox option](https://user-images.githubusercontent.com/17011743/70229736-0d3e4600-1757-11ea-9ff0-167d544efb1a.png)

Any idea to resolve this problem?

**Comment by lnxbil** [comment]
Hi and thank you for using the driver with kubernetes! It's still on my todo list :-D

I recently introduced a check that should try to detect any errors with the disk creation, so that is to blame for that. Unfortunately, it sends it's expected and actual data in the second line of the error message, that is not displayed in your output (maybe the software expects only one line of error).

Anyway, I have a possible workaround but no machine I can actually test it. Would you be so kind?

https://github.com/lnxbil/docker-machine-driver-proxmox-ve/releases/tag/possible-fix-for-16

**Comment by Sellto** [comment]
I can be the tester ;)

So, i have just tested your proposed release but that don't resolve the issue. 
However i have new informations from the logs: 

<img width="937" alt="Capture d’écran 2019-12-05 à 12 45 35" src="https://user-images.githubusercontent.com/17011743/70232977-e6374280-175d-11ea-932d-540191d4a6fe.png">

I hope it help you more.

**Comment by lnxbil** [comment]
Thank you, now with a better error message I can deal with. brb

**Comment by lnxbil** [comment]
So, another [prerelease](https://github.com/lnxbil/docker-machine-driver-proxmox-ve/releases/tag/v3-pre2)

**Comment by Sellto** [comment]
We are going forward.

The VM is correctly deploy with rancherOS.
However I have a new error :

<img width="1414" alt="Capture d’écran 2019-12-05 à 13 06 53" src="https://user-images.githubusercontent.com/17011743/70234298-a4f46200-1760-11ea-9271-aa740d6ac541.png">

I think it's a other issue and I don't know if that come from the driver. What do you think about this error?

a possible way : the name of the driver don't match...

**Comment by lnxbil** [comment]
Yes, this is a new and external error. Strange that it is found in the first place to create the VM. In which directory did you copy the driver file?

**Comment by Sellto** [comment]
It think i have a possible solution : 
change `proxmox` to `proxmoxve` into the `main.go` ... i think it can do the job

**Comment by Sellto** [comment]
> Yes, this is a new and external error. Strange that it is found in the first place to create the VM. In which directory did you copy the driver file?

In rancher you upload the driver from the interface... and then he store it somewhere... 
but i try a fork of you repo where the import name was proxmoxve and i don't have this issue. 

I think it's important to work on your repo because it is pointed by rancher.

**Comment by lnxbil** [comment]
Just to be clear, changing this works?

```diff
diff --git a/cmd/docker-machine-driver-proxmox-ve/main.go b/cmd/docker-machine-driver-proxmox-ve/main.go
index 5ca2279..7a2df1f 100644
--- a/cmd/docker-machine-driver-proxmox-ve/main.go
+++ b/cmd/docker-machine-driver-proxmox-ve/main.go
@@ -2,9 +2,9 @@ package main
 
 import (
        "github.com/docker/machine/libmachine/drivers/plugin"
-       proxmox "github.com/lnxbil/docker-machine-driver-proxmox-ve"
+       proxmoxve "github.com/lnxbil/docker-machine-driver-proxmox-ve"
 )
 
 func main() {
-       plugin.RegisterDriver(proxmox.NewDriver("default", ""))
+       plugin.RegisterDriver(proxmoxve.NewDriver("default", ""))
 }
```

**Comment by lnxbil** [comment]
Ah, nevermind. Found your fork.

**Comment by lnxbil** [comment]
So, changed it in 50146442d18c0a195bcf114e9bdcb6e772583aa8 and forgot to reference this issue.

**Comment by lnxbil** [comment]
I've not uploaded a new release yet, you're capable of building your own as you revealed above :-D

**Comment by Sellto** [comment]
i encourage you to build and create the pre-release 3... to avoid problem with our possible different golang version

**Comment by lnxbil** [comment]
> i encourage you to build and create the pre-release 3... to avoid problem with our possible different golang version

Sure thing ... [online](https://github.com/lnxbil/docker-machine-driver-proxmox-ve/releases/tag/v3-pre3).
