### ISSUE TITLE
The System isn't using disk

### ISSUE THREAD

**Issue by bemanuel** [lnxbil/docker-machine-driver-proxmox-ve#23]
After the system is created, even with disk attached the vm isn't using the disk yet. So there's a problem of disk space when run anything. There is a way to auto this process?

**Comment by lnxbil** [comment]
I assume you're running RancherOS and are using the `autoformat` Proxmox VE distribution?

**Comment by bemanuel** [comment]
No, I'll upgrade the code and change the ISO. Thanks

**Comment by lnxbil** [comment]
> No, I'll upgrade the code and change the ISO. Thanks

So is there something missing in the official file? I assumed the `autoformat` iso is to - as the name suggests - automatically formats the disks, isn't it?

**Comment by bemanuel** [comment]
The problem was that I downloaded the wrong iso.Getting autoformat, like you said, it works.
But, I need to change the Scsi Hw to Virtio.

**Comment by lnxbil** [comment]
Good to know. Should we switch to virtio as default for that, not just have a configuration flag? I was under the impression that scsi with virtio-scsi is the better and the preferred choice (PVE default) for running Linux.
