### ISSUE TITLE
Feature Request: VMID range

### ISSUE THREAD

**Issue by CarlosLVar** [lnxbil/docker-machine-driver-proxmox-ve#25]
Dear lnxbil,

Your last update was amazing, everything seems to work as it should, so thanks for that!

We were wondering if it would be possible to add a vmid range to the options?

How could I go about to do it, for me to make a pull request?

Regards,

**Comment by lnxbil** [comment]
> How could I go about to do it, for me to make a pull request?

That works as well. I do not know when I have the time to do it. At the moment, I try to build a reproducible test environment including the Rancher OS GUI.

**Comment by travisghansen** [comment]
I implemented this in #34 

```
--proxmoxve-vm-vmid-range "<low>[:<high>]"
```

**Comment by lnxbil** [comment]
So, merged and available in v4.
