### ISSUE TITLE
Discuss: Add MIT license

### ISSUE THREAD

**Issue by Psayker** [lnxbil/docker-machine-driver-proxmox-ve#27]
@lnxbil I propose to add MIT license to relieve from any duties. This would be better to explicitly declare license, because you can have some problem with law or somebody can start a lawsuit against you.

**Comment by lnxbil** [comment]
Yes, I also thought about this, but haven't decided which license to use. Other drivers I inspected use Apache and BSD. I have no problem adding MIT license to the driver.

**Comment by Psayker** [comment]
Can you add license with next your commit, it would be great.
