### ISSUE TITLE
Getting IP Address of QEMU Guest

### ISSUE THREAD

**Issue by prologic** [lnxbil/docker-machine-driver-proxmox-ve#3]
So I did a bit of research and found what I believe is a viable and reliable way of getting the IP Address of a QEMU Guest.

```#!bash
$ qm agent 302 network-get-interfaces | jq -r '.[] | select(."hardware-address" == "42:24:09:dd:1c:73") | ."ip-addresses" | .[] | ."ip-address"'
```

Basically this requires that the `qemu-guest-agent` is installed on the guest and `qemu-ga` daemon is running. You can then either run `qm agent <vmid> <command>` or probably talk tot he UNIX sokcet directly on the PRmoxox VE host.

**Comment by prologic** [comment]
A fallback mechanisms would be to run `arp -a` on the host. This gives you an output like this:

```#!bash
root@vz1:~# arp -a
? (10.0.0.14) at 36:32:31:61:32:66 [ether] on vmbr0
? (10.0.0.1) at 4c:5e:0c:a0:a6:25 [ether] on vmbr0
```

**Comment by lnxbil** [comment]
Both are viable, yet I do not know if the qemu-agent gets installed in the boot2docker iso

**Comment by prologic** [comment]
I'm actually more interested in RancherOS myself and filed rancher/os#2267 for this very reason.

I think using `qemu-guest-agent` is going to be more reliable; so I would almost make this a hard requirement that if you want to use this driver, your guest better have this agent installed and running.

**Comment by lnxbil** [comment]
Yes, I agree. I've never tried something else besides the default docker machine OS, so I'm open to this.

**Comment by prologic** [comment]
Yeah no worries. RancherOS is what I run everywhere in production. I deploy
clusters of 3-5 nodes running with Docker Swarm mode (builtin/native to
Docker engine).


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by lnxbil** [comment]
I just stumbled over your entry in RancherOS by chance .. Good to know that we're going to have support in RancherOS. I haven't found any entry in the boot2docker issue tracker about this. Are so few people using KVM/QEMU and docker?

**Comment by lnxbil** [comment]
You idea with RancherOS works perfectly. We're going to make this the default:

```
root@proxmox4 ~ > pvesh create nodes/proxmox4/qemu/7321/agent -command network-get-interfaces
200 OK
{
...
     {
         "hardware-address" : ....
         "ip-addresses" : [
            {
               "ip-address" : "1.2.3.4",
               "ip-address-type" : "ipv4",
               "prefix" : 16
            },
            ....
      },
...
}
```

**Comment by prologic** [comment]
Coool :) That is awesome!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by lnxbil** [comment]
In addtion, I just build Boot2Docker with support for QEMU Guest Agent and created a pull request in boot2docker/boot2docker#1319. This actually works right now!

**Comment by prologic** [comment]
Niiiiccee!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by lnxbil** [comment]
So, we can close this, because the detection works now.

**Comment by prologic** [comment]
Cool (y)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
