### ISSUE TITLE
Copy of Patched ISO?

### ISSUE THREAD

**Issue by Doc-Savage** [lnxbil/docker-machine-driver-proxmox-ve#6]
I have almost gotten this to work - but am having trouble building the new iso at the moment.  Do you have a copy of it somewhere that would be accessible?

-Andy

**Comment by lnxbil** [comment]
Yeah, sure. I just uploaded it to the [git where the patches are](https://github.com/lnxbil/boot2docker/releases/tag/2018-09-16).

**Comment by Doc-Savage** [comment]
Thanks!  I want to try and build it but getting a strange error when it
tries to download the kernel.

Xz says it's an unknown format and I haven't figured out why.
